### ISSUE TITLE
troll

### ISSUE THREAD

**Issue by Crystallinqq** [Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-#1]
“NOT my revesing methods”
in readme.
 u arent reversing tho? u are decompiling jar, put in intellij project, and build?

**Comment by jakepriddle** [comment]
> “NOT my revesing methods”
> in readme.
> u arent reversing tho? u are decompiling jar, put in intellij project, and build?

@Crystallinqq unblock me

**Comment by Cappinqq** [comment]
hes recreating the source using the built jar file, thats reverse engineering is it not?

**Comment by Crystallinqq** [comment]
> hes recreating the source using the built jar file, thats reverse engineering is it not?

the decompiler does all the work for him. All he is doing is fixing some errors and putting it into a forge workspace

**Comment by Gopro336** [comment]
ok il change it

**Comment by Crystallinqq** [comment]
ok thanks :3

**Comment by RunFaderZ** [comment]
cock
