### ISSUE TITLE
How do i make it onto a .jar?

### ISSUE THREAD

**Issue by RealDirt** [Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-#5]

**Comment by fuckyoudoll1** [comment]
open terminal as administrator, cd into the phobos folder, then type gradlew setupDecompWorkspace, then type gradlew build. now you built it, open your phobos folder > gradle > libs then you have the working jar there. use the release one.

**Comment by YeahOMA** [comment]
> _No description provided._

go onto my profile and find the pre built Phobos release retard
