### ISSUE TITLE
When I build this using gradle it says build failed

### ISSUE THREAD

**Issue by subtojbstaryt** [Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-#8]
Help

**Comment by tman10001** [comment]
https://github.com/Gopro336/PSA-how-to-fix-gradle-builds-feb-2021 i was the guy on the reddit btw

**Comment by wyvest** [comment]
https://github.com/Gopro336/Phobos_1.7.2-BUILDABLE-SRC-Non-Chinese-/pull/9 fixes this
